version: "3.5"

services:
  app:
    image: tcc-server-application
    container_name: tcc_server_application
    depends_on:
      - postgres
    networks:
      - tcc_network
  postgres:
    image: postgres:latest
    container_name: tcc_server_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - tcc_network
  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: tcc_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
networks:
    tcc_network: