version: "3.5"

services:
  postgres:
    image: postgres:latest
    container_name: tcc_server_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: tcc_rabbitmq
    hostname: "rabbitmq"
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
    networks:
      - my_network
  http-app:
    mem_limit: 4g
    cpus: 2
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile.http
    container_name: tcc_server_http_application
    ports:
      - "${HTTP_APP_PORT}:3000"
    networks:
      - my_network
    depends_on:
      - postgres
  grpc-app:
    mem_limit: 4g
    cpus: 2
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile.grpc
    container_name: tcc_server_grpc_application
    ports:
      - "${GRPC_APP_PORT}:3001"
    networks:
      - my_network
    depends_on:
      - postgres
  rabbitmq-app:
    mem_limit: 4g
    cpus: 2
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile.rabbitmq
    container_name: tcc_server_rabbitmq_application
    networks:
      - my_network
    depends_on:
      - postgres
      - rabbitmq
  bff-app:
    mem_limit: 4g
    cpus: 2
    build:
      context: ./
      dockerfile: ./cmd/client/Dockerfile
    container_name: tcc_client_application
    ports:
      - "${BFF_APP_PORT}:3002"
    networks:
      - my_network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
volumes:
  postgres_data:
    driver: local
networks:
  my_network:
    driver: bridge