FROM golang:latest

WORKDIR /app

COPY . /app

RUN ls -la
RUN make deps

RUN cp .env.example .env
RUN make server-build

EXPOSE 8081

ENTRYPOINT ["/app/build/tcc-server-application"]

CMD ["-type=grpc"]